# Generated by Django 4.1.1 on 2022-09-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_projetos_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
